name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file infra/template.yml \
            --stack-name playing-the-market \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides FrontendBucketName=playing-the-market-frontend-amandacot-1234

      - name: Sync frontend to S3
        run: |
          aws s3 sync frontend/ s3://playing-the-market-frontend-amandacot-1234 --delete
     # 3. Set up Docker Buildx (needed for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Log in to AWS ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 736116164611.dkr.ecr.us-east-2.amazonaws.com

      # 5. Run deployment script
      - name: Deploy AWS resources
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
          
